---
name: Build

on:
  push:
    branches:
    - '**'
    - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test build
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .
